previewsEnabled: true
databases:
  - name: medusa-db-blueprint
    region: virginia
    ipAllowList: []
    postgresMajorVersion: "16"
services:
- type: web
  name: medusa-eats-api-blueprint-pineapple
  runtime: node
  repo: https://github.com/lexpierce/medusa-eats-demo
  plan: standard
  envVars:
  - key: REDIS_URL
    fromService:
      name: medusa-redis-blueprint
      type: redis
      property: connectionString
  - key: FRONTEND_URL
    value: https://medusa-eats-demo-blueprint-pineapple.onrender.com 
  - key: DATABASE_URL
    fromDatabase:
      name: medusa-db-blueprint
      property: connectionString
  - key: JWT_SECRET
    generateValue: true
  region: virginia
  buildCommand: yarn install; yarn run build
  startCommand: yarn run start
  preDeployCommand: yarn run setup-db
  scaling:
    minInstances: 1
    maxInstances: 5
    targetCPUPercent: 80
    targetMemoryPercent: 80
  rootDir: ./backend
- type: web
  name: medusa-eats-demo-blueprint-pineapple
  runtime: node
  repo: https://github.com/lexpierce/medusa-eats-demo
  plan: starter
  envVars:
  - key: BACKEND_URL
    value: https://medusa-eats-api-blueprint-pineapple.onrender.com
  - key: JWT_SECRET
    fromService:
      name: medusa-eats-api-blueprint-pineapple
      type: web
      envVarKey: JWT_SECRET
  region: virginia
  buildCommand: yarn install; yarn run build
  startCommand: yarn run start
  rootDir: ./frontend
- type: redis
  name: medusa-redis-blueprint
  plan: starter
  region: virginia
  maxmemoryPolicy: allkeys-lru
  ipAllowList: []
version: "1"
