previewsEnabled: true
databases:
  - name: medusa-db
    databaseName: medusa_db_ghqs
    user: medusa_db_ghqs_user
    region: virginia
    ipAllowList:
    - source: 0.0.0.0/0
      description: everywhere
    postgresMajorVersion: "16"
services:
- type: web
  name: medusa-api
  runtime: node
  repo: https://github.com/lexpierce/medusa-eats-demo
  plan: pro
  envVars:
  - key: REDIS_URL
    fromService:
      name: medusa-redis
      type: redis
      property: connectionString
  - key: FRONTEND_URL
    sync: false
  - key: DATABASE_URL
    fromDatabase:
      name: medusa-db
      property: connectionString
  - fromGroup: Medusa Eats Secrets
  region: virginia
  buildCommand: yarn install; yarn run build
  startCommand: yarn run start
  scaling:
    minInstances: 1
    maxInstances: 5
    targetCPUPercent: 80
    targetMemoryPercent: 80
  rootDir: ./backend
- type: web
  name: medusa-frontend
  runtime: node
  repo: https://github.com/lexpierce/medusa-eats-demo
  plan: pro
  envVars:
  - key: BACKEND_URL
    sync: false
  - fromGroup: Medusa Eats Secrets
  region: virginia
  buildCommand: yarn install; yarn run build
  startCommand: yarn run start
  rootDir: ./frontend
- type: redis
  name: medusa-redis
  plan: starter
  region: virginia
  maxmemoryPolicy: allkeys-lru
  ipAllowList: []
version: "1"
