# -----
# databases and IP restrictions
databases:
  - name: medusa-eats
    databaseName: medusa
    ipAllowList: [] # only allow internal connections

# -----
# preview environments for services
previewsEnabled: true
previewsExpireAfterDays: 3

services:
  # redis
  - type: redis
    name: medusa-redis
    ipAllowList: # Allow external connections from only these CIDR blocks
      - source: 203.0.113.4/30
        description: office
    region: oregon       # Default: oregon
    plan: starter        # Default: starter
    previewPlan: starter # Default: use the value for 'plan'
    maxmemoryPolicy: allkeys-lru # Default: allkeys-lru)

  - type: web   # front end
    repo: https://github.com/renderinc/gartner-demo-2024-medusa-eats
    rootDir: ./frontend
    name: medusa-frontend
    env: node
    plan: starter
    buildCommand: cd frontend; bash ./build.sh
    startCommand: cd frontend; bash ./start.sh
    envVars:
      - key: NODE_ENV
        value: production

  - type: web   # back end
    plan: starter plus
    previewPlan: starter
    repo: https://github.com/renderinc/gartner-demo-2024-medusa-eats
    rootDir: ./backend
    name: gartner-backend
    env: node
    buildCommand: cd backend; bash ./build.sh
    startCommand: cd backend; bash ./start.sh
    envVars:
      - key: FRONTEND_HOSTPORT
        fromService:
          type: web
          name: medusa-frontend
          property: hostport
      - key: DATABASE_URL
        fromDatabase:
          name: medusa-eats
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: medusa-redis
          property: connectionString
