# -----
# databases and IP restrictions
databases:
  - name: medusa-eats
    databaseName: medusa
    ipAllowList: [] # only allow internal connections

# -----
# preview environments for services
previewsEnabled: true
previewsExpireAfterDays: 3

services:
  # redis
  - type: redis
    name: medusa-redis
    ipAllowList: # Allow external connections from only these CIDR blocks
      - source: 203.0.113.4/30
        description: office
    region: oregon       # Default: oregon
    plan: pro            # Default: starter
    previewPlan: starter # Default: use the value for 'plan'
    maxmemoryPolicy: allkeys-lru # Default: allkeys-lru)
    disk:
      name: redis-data
      mountPath: /var/lib/redis
      sizeGB: 2 # optional

  # front end
  - type: web
    name: medusa-frontend
    env: node
    plan: starter
    buildCommand: yarn; yarn build
    startCommand: yarn start
    envVars:
    - key: NODE_ENV
      value: production

  # back end
  - type: web
    plan: starter plus
    previewPlan: starter
    name: gartner-backend
    env: node
    buildCommand: cd backend && yarn
    startCommand: cd backend && export FRONTEND_URL="https://$FRONTEND_HOSTPORT" && yarn start
    - key: FRONTEND_HOSTPORT
      fromService:
        name: medusa-frontend
        property: hostport
    - key: DATABASE_URL
      fromDatabase:
        name: medusa-eats
        property: connectionString
    - key: REDIS_URL
      fromService:
        type: redis
        name: medusa-redis
        property: connectionString
